### ISSUE TITLE
F# editor conflict

### ISSUE THREAD

**Issue by xperiandri** [shaneray/ShaneSpace.VisualStudio.InvisibleCharacterVisualizer#1]
In VS 2017 this extension conflicts with F# editor and disables all its features and does not allow to edit .fs files.

**Comment by shaneray** [comment]
@xperiandri I am very sorry to hear this.  I have not worked with F# yet.  I am upgrading to VS 2017 RTM and installing F# tooling now.  Once installed I will see if I can track down the issue.  Thanks for the report!

**Comment by shaneray** [comment]
I got VS 2017 RTM installed, and created a F# console application, but was unable to produce the issue you described. What features are disabled?  What do you mean by "does not allow to edit .fs files"?  Only issue I have noticed so far is if you type further down the line it will place a bunch of hidden characters (tab) automatically as shown below.
![image](https://cloud.githubusercontent.com/assets/482797/23832577/75374b1a-070d-11e7-950a-d4845b0ac41c.png)

**Comment by shaneray** [comment]
I have updated the extension to version 1.1 -- This update does not consider `0x09` (TAB) as an invisible character.  Try the new version and let me know if the issue persists.  I am thinking it may be a conflict with another extension you have installed as I am able to open a F# file with no issues.

**Comment by xperiandri** [comment]
Interesting. When I opened .fs file navigation bar did not appear and focus moved by invisible characters placeholders instead of text.

**Comment by xperiandri** [comment]
Yes, it works now

**Comment by shaneray** [comment]
@xperiandri glad to hear it!  Hopefully this extension helps you.  Please rate it in the VS gallery if you get a chance.  Closing this issue.

**Comment by xperiandri** [comment]
Yep, I will use it for a week to be sure that I can rate it 5 stars.
