### ISSUE TITLE
Not Installing into Visual Studio Code

### ISSUE THREAD

**Issue by borpin** [shaneray/ShaneSpace.VisualStudio.InvisibleCharacterVisualizer#11]
Not sure if it should but it will not install in VS Code from download file.

![image](https://user-images.githubusercontent.com/1322749/47245964-5ddbce00-d3f3-11e8-8d1a-511cb690d494.png)

**Comment by shaneray** [comment]
This is expected as this is a “Visual Studio” extension, not “VS Code”.
