### ISSUE TITLE
VS 2019 support

### ISSUE THREAD

**Issue by xperiandri** [shaneray/ShaneSpace.VisualStudio.InvisibleCharacterVisualizer#12]
https://blogs.msdn.microsoft.com/visualstudio/2018/09/26/how-to-upgrade-extensions-to-support-visual-studio-2019/

**Comment by onlinestatements** [comment]
I second the need to have this compatible with VS2019!

**Comment by jzabroski** [comment]
@shaneray  I am looking to move to VS2019 this week, so let me know what I can do to help.

**Comment by shaneray** [comment]
I took a stab at updating this weekend, but it did not run in the 2019 experimental instance.  I will circle back around to this and see if I can figure out whats going on soon.  I accept pull requests if anyone gets this working.

**Comment by shaneray** [comment]
Visual Studio 2019 is now supported in version 1.4 -- Thanks for the requests!

https://marketplace.visualstudio.com/items?itemName=ShaneRay.InvisibleCharacterVisualizer

**Comment by jzabroski** [comment]
Thanks, Shane!
