### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by cgtyoder** [shaneray/ShaneSpace.VisualStudio.InvisibleCharacterVisualizer#15]
I highly recommend you add a license to both this code and the VS Extension ([MIT License](https://opensource.org/licenses/MIT) suggested), so that it can be (safely) used by people concerned about licensing (which should be everyone). Will give us all piece of mind that you're not gonna come after the people using it. :grin:

**Comment by shaneray** [comment]
Thanks for the suggestion!  I will try to add at some point, but extremely busy … PR is welcome!
