### ISSUE TITLE
Low performance

### ISSUE THREAD

**Issue by xperiandri** [shaneray/ShaneSpace.VisualStudio.InvisibleCharacterVisualizer#5]
I don't know why but this extension significantly lowers performance

**Comment by shaneray** [comment]
Could you please provide more details?

What version of VS?
What operations are having performance issues? Start up?  Opening files? Editing files? Large files?

I am curious about this statement as you opened another issue about the extension crashing.  This means the extension has not been running and should not be causing any performance issues.

**Comment by shaneray** [comment]
I have made an adjustment that may improve performance issues if there were any.
Please re-open ticket if you are still experiencing performance issues after upgrading.
Fixed by 1.3 release.

**Comment by xperiandri** [comment]
Looks like it's fine now
