### ISSUE TITLE
Make it compatible with Visual Studio Code (VS Code)

### ISSUE THREAD

**Issue by yphastos** [shaneray/ShaneSpace.VisualStudio.InvisibleCharacterVisualizer#8]
I found out it only works with the "main" Visual Studio (2015,2017, according to the marketplace). 

Could you also make it compatible with Visual Studio Code (aka VS Code)?

Thanks

**Comment by Mon-Tea** [comment]
We need this extension ... make it please compatible with VS Code...

**Comment by shaneray** [comment]
I have no experience developing extensions for VS code and it’s unlikely I will get around to porting this over.
